### ISSUE TITLE
[React][Dialog] Controlled Dialog is not fully controlled

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/zag#1027]
### Description

Hi!

When using the `Dialog` component in controlled mode, there is an issue with the close behavior. When in controlled mode, I expect to fully control "how" the dialog will be closed but that's not the case currently as the dialog will always be closed internally when clicking on the `CloseTrigger` component, using the Esc key, or clicking on the backdrop.

As a workaround, I could listen for the `onOpenChange` property and update the parent state, but it does not make any sense as  the open state of the dialog should be "controlled" by the parent directly. Also, it causes an extra render because we're trying to sync both the state of the parent and the internal dialog state.

When looking at other component libraries (MUI, HeadlessUI, etc.), a dialog in controlled mode won't be closed unless the parent sets the proper `open` value.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/s/ark-ui-dialog-controlled-2l28fg?file=/src/Dialog.tsx

### Steps to Reproduce

1. Go to the reproduction link
2. Open the dialog
3. Close the dialog by clicking on the close button
4. Check the console logs, you should see a message indicating that the `onOpenChange` hander has been called with the `false` value meaning the internal dialog state has changed
5. Try to open the dialog again
6. The dialog won't open because the parent state is not in sync.

**Expected behavior**
The dialog should not close in this case when I click on the close button because I don't set the `open` props to `false`.

### Ark UI Version

1.0.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 119

### Additional Information

It's possible that we have the same issue with other components that have a controlled mode and overlay.

**Comment by its-jman** [comment]
Was very confused for quite a bit before finding this issue, I'd also fully expect a component that is being controlled to respect it's props passed in.

**Comment by TreeOfLearning** [comment]
@cschroeter Apologies for the mention, but is there any update on this? This is now two months old but the issue remains: you cannot control the visibility of a dialog externally. The [controlled dialog example](https://ark-ui.com/docs/components/dialog#api-reference) given on the ark-ui documentation simply does not work - the dialog opens once, then once closed, will never open again. There is clearly a state issue here.

**Comment by juliomuhlbauer** [comment]
I am coming with a fix

**Comment by cschroeter** [comment]
@TreeOfLearning 

There is an internal proposal whether or not we should replace the current state machine engine with XState v5
So depending on the outcome of this proposal this issue can and will be resolved.

Please correct me if I said sth wrong cc @segunadebayo

**Comment by juliomuhlbauer** [comment]
It would be amazing to use xstate. It would be a lot easier to mantain because I already use Xstate!

**Comment by juliomuhlbauer** [comment]
If anyone can help I opened a PR? https://github.com/chakra-ui/zag/pull/1161

**Comment by juliomuhlbauer** [comment]
This was fixed?

**Comment by VictorienDruon** [comment]
As of today, the [controlled dialog example](https://ark-ui.com/docs/components/dialog#api-reference) given on the ark-ui documentation still does not work. Any updates on that?

**Comment by segunadebayo** [comment]
That’s strange @VictorienDruon. Do you have a reproduction?
