### ISSUE TITLE
Nested menu not working since Svelte 5.33.5

### ISSUE THREAD

**Issue by rChaoz** [chakra-ui/zag#2502]
# 🐛 Bug report

The menu works correctly with Svelte 5.33.4, and is broken in 5.33.5. After some debugging, it seems like the `parent` ref remains null, even when set using `onMount`. This affects multiple things, but, for example, the `pointerleave` event no longer hides the nested menu, causing it to remain visible forever.

## 💥 Steps to reproduce

Instructions are inside the REPL below

## 💻 Link to reproduction

https://svelte.dev/playground/72de13d6bb994daeabdc464626cd9eec?version=5.33.14

**Comment by segunadebayo** [comment]
It appears to be already fixed in the latest Svelte (5.33.15). I've bumped the version, and it works correctly.

Please bump the version and try again.

> Side note: Svelte releases have been quite volatile lately. We'll keep an eye on the updates

**Comment by rChaoz** [comment]
Hi thanks for the response! However the issue is not fixed, maybe you tried in Chrome/Chromium? The issue is Firefox-only.

**Comment by rChaoz** [comment]
@segunadebayo could you maybe please try reproducing using FF on latest Svelte version and re-open this, thanks! If you can't reproduce it let me know so I'll take a better look
