### ISSUE TITLE
[Bug] Combobox cursor moves to end of input

### ISSUE THREAD

**Issue by dennemark** [chakra-ui/zag#660]
# 🐛 Bug report

Changing word within combobox input moves the cursor to the end of the input.

## 💥 Steps to reproduce

can be tried on: https://zagjs.com/components/react/combobox

![backspace-bug](https://github.com/chakra-ui/zag/assets/29654902/e293bee7-3813-4000-8eee-f598894b30df)

## 🧐 Expected behavior

Cursor stays at same place.

## 🧭 Possible Solution

https://github.com/facebook/react/issues/955#issuecomment-469352730

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.9.2          |
| Browser          |  chrome 113          |
| Operating System |   Win11         |

**Comment by segunadebayo** [comment]
Good catch @dennemark.

I pushed a fix for this yesterday, will release a patch shortly.

**Comment by dennemark** [comment]
@segunadebayo is this one really fixed already? In my project it is still happening with dev and latest version. And zag.js website still has the issue.

**Comment by dennemark** [comment]
All good! Seems to work now on v.0.10.2 :) Thanks a lot!
